// lang.js — bilingual (Vietnamese / English) translations
const LANG = {
  vi: {
    tab_view: '📊 Xem Dữ Liệu', tab_compare: '🔄 So Sánh', tab_import: '📥 Nhập Dữ Liệu', tab_manage: '⚙️ Quản Lý',
    lang_toggle: '🌐 EN',
    loading: 'Đang load dữ liệu, vui lòng đợi...',
    select_server: '🗺 Chọn Server', no_data_admin: 'Chưa có dữ liệu — Admin cần nhập trước',
    server_days: 'ngày', server_prefix: 'Server',
    select_date: '📅 Chọn Ngày',
    stat_players: 'Người Chơi', stat_alliances: 'liên minh',
    stat_total_power: 'Tổng Lực Chiến', stat_total_merit: 'Tổng Công Trạng',
    stat_total_kill: 'Tổng Tiêu Diệt', stat_total_heal: 'Tổng Chữa Lính', stat_total_mana: 'Tổng Tiêu Mana',
    ranking: '📊 Bảng Xếp Hạng', search_placeholder: '🔍 Tìm tên / liên minh / ID...',
    fmt_short: '🔢 Rút gọn', fmt_full: '🔢 Đầy đủ',
    col_name: 'Tên', col_alliance: 'Liên Minh',
    col_merit: 'Công Trạng', col_merit_rate: 'Tỉ Lệ CT', col_power: 'Lực Chiến', col_power_max: 'Lực Chiến Max',
    col_kill: 'Tiêu Diệt', col_dead: 'Tử Trận', col_heal: 'Chữa Lính', col_mana_spend: 'Tiêu Mana',
    col_gold_spend: 'Vàng Tiêu', col_wood_spend: 'Gỗ Tiêu', col_stone_spend: 'Đá Tiêu', col_gem_spend: 'Gem Tiêu',
    col_gold_gather: 'Vàng Thu', col_wood_gather: 'Gỗ Thu', col_stone_gather: 'Đá Thu',
    col_mana_gather: 'Mana Thu', col_gem_gather: 'Gem Thu',
    top10_before: 'Giá Trị Trước', top10_after: 'Giá Trị Sau', top10_diff: 'Chênh Lệch',
    not_found_badge: '❌ Không tìm thấy', players_count: 'người chơi',
    not_found_row: '😔 Không tìm thấy — thử từ khác?',
    cmp_title: '🔄 So Sánh Giữa Hai Ngày', cmp_date_before: 'Ngày Trước', cmp_date_after: 'Ngày Sau',
    cmp_total_changes: 'Thay Đổi Tổng Cộng', cmp_date_before_short: 'Trước', cmp_date_after_short: 'Sau',
    cmp_change: 'Thay đổi', cmp_detail: 'Chi Tiết Từng Người', cmp_search: '🔍 Tìm người chơi...',
    cmp_top10: '🏆 Top 10 Theo Chênh Lệch', cmp_select_diff: 'Vui lòng chọn 2 ngày khác nhau',
    no_data_short: 'Không có dữ liệu', no_data_cmp: 'Chưa có dữ liệu',
    dir_desc: '↓ Cao → Thấp', dir_asc: '↑ Thấp → Cao', view_detail: 'Xem chi tiết',
    top10_merit: '▲ Công Trạng', top10_kill: '▲ Tiêu Diệt', top10_heal: '▲ Chữa Lính',
    top10_dead: '▲ Tử Trận', top10_power: '▲ Lực Chiến', top10_mana: '▲ Tiêu Mana', top10_mana_gather: '▲ Thu Mana',
    section_battle: '⚔️ Chiến Đấu', section_spend: '💰 Tiêu Thụ', section_gather: '🌾 Thu Thập',
    field_alliance: 'Liên Minh', field_merit: 'Công Trạng', field_merit_rate: 'Tỉ Lệ CT',
    field_power: 'Lực Chiến', field_power_max: 'Lực Chiến Max', field_kill: 'Tiêu Diệt',
    field_dead: 'Tử Trận', field_heal: 'Chữa Lính',
    field_gold: 'Vàng', field_wood: 'Gỗ', field_stone: 'Đá', field_mana: 'Mana', field_gem: 'Gem',
    diff_tip: '💡 Tất cả số hiển thị dạng <b style="color:var(--gold)">đầy đủ</b> · Trước → Sau → Chênh lệch',
    diff_col_diff: '📊 Chênh Lệch',
    cp_default: 'Mặc định', cp_extra: 'Tùy chọn thêm', cp_all: 'Tất cả', cp_none: 'Bỏ thêm', cp_reset: 'Mặc định', cp_col: 'Cột',
    import_title: '📥 Nhập Dữ Liệu Mới', import_btn: '⚔️ Nhập Dữ Liệu', import_clear_btn: '🗑 Xóa',
    import_empty: 'Vui lòng dán dữ liệu vào ô trên!', import_replaced: '🔄 Đã thay thế', import_added: '✅ Đã thêm mới',
    import_replace_label: 'Ngày trùng', import_replace_desc: 'thay thế', import_new_label: 'Ngày mới', import_new_desc: 'thêm lịch sử',
    import_guide_title: '📋 Hướng Dẫn',
    import_guide: '1️⃣ Lấy dữ liệu từ Tabi mỗi ngày, dán vào ô trên<br>2️⃣ Nhấn <b style="color:var(--gold)">Nhập Dữ Liệu</b> — tự nhận server &amp; ngày<br>3️⃣ Lưu Firebase — mọi người thấy ngay lập tức<br>4️⃣ Người dùng thường chỉ thấy Xem &amp; So Sánh',
    manage_title: '⚙️ Quản Lý Dữ Liệu', manage_days: 'ngày', manage_records: 'bản ghi',
    manage_delete_server_btn: '🗑 Xóa Server',
    backup_title: '💾 Backup', backup_export_btn: '⬇️ Xuất JSON',
    backup_desc: 'Backup dữ liệu ra file JSON dự phòng.', backup_clear_btn: '🗑 Xóa Toàn Bộ',
    confirm_delete_date: (s, d) => `Xóa Server ${s} ngày ${d}?`,
    confirm_delete_server: s => `Xóa toàn bộ Server ${s}? Không thể hoàn tác!`,
    confirm_clear: 'Xóa TOÀN BỘ? Không thể hoàn tác!',
    admin_logout: 'Đăng Xuất', admin_login_btn: '🔒 Admin',
    login_submitting: 'Đang đăng nhập...', login_submit: 'Đăng Nhập', login_empty: 'Vui lòng nhập đầy đủ!',
    err_save: 'Lỗi lưu: ', err_delete: 'Lỗi xóa: ',
    excel_merit_before: 'CT Trước', excel_merit_after: 'CT Sau', excel_merit_rate_calc: 'Tỉ Lệ CT (%)',
    excel_title: 'Xuất Danh Sách Excel', excel_pwd_subtitle: 'Nhập mật khẩu để tiếp tục',
    excel_col_subtitle: 'Chọn cột và tùy chọn xuất', excel_pwd_label: 'Mật Khẩu',
    excel_pwd_input: 'Nhập mật khẩu...', excel_pwd_confirm: 'Xác Nhận',
    excel_pwd_err: '❌ Mật khẩu không đúng!', excel_col_title: '📋 Chọn Cột Xuất',
    excel_sort_label: '📊 Sắp xếp theo', excel_dir_label: '↕ Thứ tự',
    excel_data_label: 'Dữ liệu xuất (chênh lệch):', excel_cancel: 'Hủy', excel_export_btn: '⬇️ Xuất File Excel',
    excel_no_col: 'Vui lòng chọn ít nhất 1 cột!', excel_no_data: 'Vui lòng chọn 2 ngày để so sánh trước!',
    excel_btn: '📊 Xuất Excel', excel_info_title: 'Alliance Tracker — Chênh Lệch 2 Ngày',
    excel_info_server: 'Server:', excel_info_before: 'Ngày trước:', excel_info_after: 'Ngày sau:', excel_info_export: 'Xuất lúc:', excel_info_date: 'Ngày:',
    excel_view_title: '📥 Xuất Excel Theo Ngày', excel_view_data_label: 'Dữ liệu xuất (theo ngày):', excel_view_no_data: 'Vui lòng chọn server và ngày trước!',
    tab_alliance: '🏰 Server',
    alliance_title: '🏰 Bảng Xếp Hạng Tất Cả Server',
    alliance_latest: 'Dữ liệu ngày mới nhất:',
    alliance_view_members: '👤 Thành Viên',
    alliance_view_servers: '🏰 Xếp Hạng Server',
    alliance_top500: 'Top 500',
    col_players: 'Số Người',
    alliance_from_date: 'Từ ngày',
    alliance_to_date: 'Đến ngày',
    alliance_latest_label: 'Mới nhất',
    alliance_growth_mode: 'Đang xem tăng trưởng',
    alliance_mode_total: '📊 Toàn bộ',
    alliance_mode_growth: '📈 Tăng trưởng',
    alliance_pick_from: 'Chọn "Từ ngày" để xem tăng trưởng',
    footer_contact: 'Liên hệ thêm data cho server của bạn:',
  },
  en: {
    tab_view: '📊 View Data', tab_compare: '🔄 Compare', tab_import: '📥 Import Data', tab_manage: '⚙️ Manage',
    lang_toggle: '🌐 VI',
    loading: 'Loading data, please wait...',
    select_server: '🗺 Select Server', no_data_admin: 'No data yet — Admin needs to import first',
    server_days: 'days', server_prefix: 'Server',
    select_date: '📅 Select Date',
    stat_players: 'Players', stat_alliances: 'alliances',
    stat_total_power: 'Total Power', stat_total_merit: 'Total Merit',
    stat_total_kill: 'Total Kills', stat_total_heal: 'Total Heals', stat_total_mana: 'Total Mana Spent',
    ranking: '📊 Ranking', search_placeholder: '🔍 Search name / alliance / ID...',
    fmt_short: '🔢 Short', fmt_full: '🔢 Full',
    col_name: 'Name', col_alliance: 'Alliance',
    col_merit: 'Merit', col_merit_rate: 'Merit Rate', col_power: 'Power', col_power_max: 'Max Power',
    col_kill: 'Kills', col_dead: 'Deaths', col_heal: 'Heals', col_mana_spend: 'Mana Spent',
    col_gold_spend: 'Gold Spent', col_wood_spend: 'Wood Spent', col_stone_spend: 'Stone Spent', col_gem_spend: 'Gem Spent',
    col_gold_gather: 'Gold Gathered', col_wood_gather: 'Wood Gathered', col_stone_gather: 'Stone Gathered',
    col_mana_gather: 'Mana Gathered', col_gem_gather: 'Gem Gathered',
    top10_before: 'Value Before', top10_after: 'Value After', top10_diff: 'Difference',
    not_found_badge: '❌ Not found', players_count: 'players',
    not_found_row: '😔 Not found — try another keyword?',
    cmp_title: '🔄 Compare Between Two Dates', cmp_date_before: 'Earlier Date', cmp_date_after: 'Later Date',
    cmp_total_changes: 'Total Changes', cmp_date_before_short: 'Before', cmp_date_after_short: 'After',
    cmp_change: 'Change', cmp_detail: 'Per-Player Details', cmp_search: '🔍 Search player...',
    cmp_top10: '🏆 Top 10 by Difference', cmp_select_diff: 'Please select 2 different dates',
    no_data_short: 'No data', no_data_cmp: 'No data yet',
    dir_desc: '↓ High → Low', dir_asc: '↑ Low → High', view_detail: 'View details',
    top10_merit: '▲ Merit', top10_kill: '▲ Kills', top10_heal: '▲ Heals',
    top10_dead: '▲ Deaths', top10_power: '▲ Power', top10_mana: '▲ Mana Spent', top10_mana_gather: '▲ Mana Gathered',
    section_battle: '⚔️ Battle', section_spend: '💰 Spending', section_gather: '🌾 Gathering',
    field_alliance: 'Alliance', field_merit: 'Merit', field_merit_rate: 'Merit Rate',
    field_power: 'Power', field_power_max: 'Max Power', field_kill: 'Kills',
    field_dead: 'Deaths', field_heal: 'Heals',
    field_gold: 'Gold', field_wood: 'Wood', field_stone: 'Stone', field_mana: 'Mana', field_gem: 'Gem',
    diff_tip: '💡 All numbers shown in <b style="color:var(--gold)">full</b> · Before → After → Difference',
    diff_col_diff: '📊 Difference',
    cp_default: 'Default', cp_extra: 'Extra columns', cp_all: 'All', cp_none: 'None', cp_reset: 'Default', cp_col: 'Cols',
    import_title: '📥 Import New Data', import_btn: '⚔️ Import Data', import_clear_btn: '🗑 Clear',
    import_empty: 'Please paste data into the field above!', import_replaced: '🔄 Replaced', import_added: '✅ Added',
    import_replace_label: 'Duplicate date', import_replace_desc: 'will replace', import_new_label: 'New date', import_new_desc: 'add to history',
    import_guide_title: '📋 Guide',
    import_guide: '1️⃣ Get data from Tabi daily, paste it above<br>2️⃣ Click <b style="color:var(--gold)">Import Data</b> — server &amp; date auto-detected<br>3️⃣ Saves to Firebase — everyone sees it instantly<br>4️⃣ Regular users only see View &amp; Compare',
    manage_title: '⚙️ Manage Data', manage_days: 'days', manage_records: 'records',
    manage_delete_server_btn: '🗑 Delete Server',
    backup_title: '💾 Backup', backup_export_btn: '⬇️ Export JSON',
    backup_desc: 'Backup data to a JSON file.', backup_clear_btn: '🗑 Delete All',
    confirm_delete_date: (s, d) => `Delete Server ${s} on date ${d}?`,
    confirm_delete_server: s => `Delete entire Server ${s}? Cannot be undone!`,
    confirm_clear: 'Delete EVERYTHING? Cannot be undone!',
    admin_logout: 'Logout', admin_login_btn: '🔒 Admin',
    login_submitting: 'Logging in...', login_submit: 'Login', login_empty: 'Please fill in all fields!',
    err_save: 'Save error: ', err_delete: 'Delete error: ',
    excel_merit_before: 'Merit Before', excel_merit_after: 'Merit After', excel_merit_rate_calc: 'Merit Rate (%)',
    excel_title: 'Export Excel', excel_pwd_subtitle: 'Enter password to continue',
    excel_col_subtitle: 'Choose columns to export', excel_pwd_label: 'Password',
    excel_pwd_input: 'Enter password...', excel_pwd_confirm: 'Confirm',
    excel_pwd_err: '❌ Wrong password!', excel_col_title: '📋 Select Columns',
    excel_sort_label: '📊 Sort by', excel_dir_label: '↕ Order',
    excel_data_label: 'Export data (difference):', excel_cancel: 'Cancel', excel_export_btn: '⬇️ Export Excel',
    excel_no_col: 'Please select at least 1 column!', excel_no_data: 'Please select 2 dates to compare first!',
    excel_btn: '📊 Export Excel', excel_info_title: 'Alliance Tracker — Difference Between 2 Dates',
    excel_info_server: 'Server:', excel_info_before: 'Date before:', excel_info_after: 'Date after:', excel_info_export: 'Exported at:', excel_info_date: 'Date:',
    excel_view_title: '📥 Export Excel by Date', excel_view_data_label: 'Export data (snapshot):', excel_view_no_data: 'Please select a server and date first!',
    tab_alliance: '🏰 Server',
    alliance_title: '🏰 All-Server Ranking',
    alliance_latest: 'Latest data date:',
    alliance_view_members: '👤 Members',
    alliance_view_servers: '🏰 Server Ranking',
    alliance_top500: 'Top 500',
    col_players: 'Players',
    alliance_from_date: 'From date',
    alliance_to_date: 'To date',
    alliance_latest_label: 'Latest',
    alliance_growth_mode: 'Viewing growth',
    alliance_mode_total: '📊 All data',
    alliance_mode_growth: '📈 Growth',
    alliance_pick_from: 'Select "From date" to view growth',
    footer_contact: 'Contact for data on your server:',
  }
};

let _lang = localStorage.getItem('lang') || 'vi';
export function getLang() { return _lang; }
export function setLang(l) { _lang = l; localStorage.setItem('lang', l); }
export function T(key) { return (LANG[_lang]?.[key]) ?? (LANG.vi[key] ?? key); }